configMapGenerator:
- name: environment
  envs:
  - environment.env
vars:
- name: ARGOCD_APP_NAMESPACE
  objref:
    kind: ConfigMap
    name: environment
    apiVersion: v1
  fieldref:
    fieldpath: data.ARGOCD_APP_NAMESPACE
configurations:
- configuration.yaml
