apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: haproxy
  name: haproxy
spec:
  running: true
  dataVolumeTemplates:
    - apiVersion: 'cdi.kubevirt.io/v1beta1'
      kind: 'DataVolume'
      metadata:
        name: 'haproxy-pvc'
      spec:
        source:
          pvc:
            name: 'rocky9-latest'
            namespace: $(ARGOCD_APP_NAMESPACE)
        storage:
          resources:
            requests:
              storage: '10Gi'  
  template:
    metadata:
      labels:
        kubevirt.io/vm: haproxy
    spec:
      domain:
        machine:
          type: pc-q35-rhel8.6.0
        cpu:
          cores: 1
        devices:
          disks:
          - name: pvcdisk
            disk:
              bus: virtio
          - disk:
              bus: virtio
            name: cloudinitdisk                
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 2Gi
      networks:
      - name: default
        pod: {}
      volumes:
      - name: pvcdisk
        dataVolume:
          name: haproxy-pvc
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            user: centos
            password: P@ssw0rd
            chpasswd: { expire: False }
            runcmd:
            - yum install -y haproxy
            - systemctl enable --now haproxy
            write_files:
            - content: |
                global
                  log         127.0.0.1 local2
                  chroot      /var/lib/haproxy
                  pidfile     /var/run/haproxy.pid
                  maxconn     4000
                  user        haproxy
                  group       haproxy
                  daemon
              defaults
                  mode                    http
                  log                     global
                  option                  httplog
                  option                  dontlognull
                  option http-server-close
                  option forwardfor       except 127.0.0.0/8
              frontend main
                  bind *:80
                  default_backend             app
              backend app
                  balance     roundrobin
                  server  web01 web01:80 check
                  server  web02 web02:80 check          
              path: /etc/haproxy/haproxy.cfg
        name: cloudinitdisk          
      evictionStrategy: LiveMigrate
