apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: environment
  envs:
  - environment.env
varReference:
- path: spec/dataVolumeTemplates[]/spec/source/pvc/namespace
  kind: VirtualMachine
vars:
- name: ARGOCD_APP_NAMESPACE
  objref:
    kind: ConfigMap
    name: environment
    apiVersion: v1
  fieldref:
    fieldpath: data.ARGOCD_APP_NAMESPACE
resources:
- datavolume.yaml
- haproxy-vm.yaml
- web01-vm.yaml
- web02-vm.yaml
- services.yaml
- route.yaml
