---
apiVersion: v1
kind: Service
metadata:
  name: web01
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    vm.cnv.io/name: web01
---    
apiVersion: v1
kind: Service
metadata:
  name: web02
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    vm.cnv.io/name: web02
---
apiVersion: v1
kind: Service
metadata:
  name: haproxy
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    vm.cnv.io/name: haproxy
