apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: web02
  name: web02
spec:
  running: true
  dataVolumeTemplates:
    - apiVersion: 'cdi.kubevirt.io/v1beta1'
      kind: 'DataVolume'
      metadata:
        name: 'web02-pvc'
        namespace: $(ARGOCD_APP_NAMESPACE)
      spec:
        source:
          pvc:
            name: 'rocky9-latest'
        storage:
          resources:
            requests:
              storage: '10Gi'    
  template:
    metadata:
      labels:
        kubevirt.io/vm: web02
    spec:
      domain:
        machine:
          type: pc-q35-rhel8.6.0
        cpu:
          cores: 1
        devices:
          disks:
          - name: pvcdisk
            disk:
              bus: virtio
          - disk:
              bus: virtio
            name: cloudinitdisk              
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 2Gi
      networks:
      - name: default
        pod: {}
      volumes:
      - name: pvcdisk
        dataVolume:
          name: web02-pvc
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            user: centos
            password: P@ssw0rd
            chpasswd: { expire: False }
            runcmd:
              - yum install -y httpd
              - echo "Hello from web02" > /var/www/html/index.html
              - systemctl enable --now httpd
        name: cloudinitdisk          
      evictionStrategy: LiveMigrate
