apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: microshift
  name: microshift
spec:
  running: true
  dataVolumeTemplates:
    - apiVersion: 'cdi.kubevirt.io/v1beta1'
      kind: 'DataVolume'
      metadata:
        name: 'microshift-pvc'
      spec:
        source:
          pvc:
            name: 'rhel-8.7'
            namespace: cnv-images
        storage:
          resources:
            requests:
              storage: '20Gi'  
  template:
    metadata:
      labels:
        kubevirt.io/vm: microshift
    spec:
      domain:
        machine:
          type: pc-q35-rhel8.6.0
        cpu:
          cores: 1
        devices:
          disks:
          - name: pvcdisk
            disk:
              bus: virtio
          - target:
              dev: vdb
            cloudinit:
              nocloud:
                userDataSecretRef: microshift-userdata
            name: ansiblecloudinit
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 2Gi
      networks:
      - name: default
        pod: {}
      volumes:
      - name: pvcdisk
        dataVolume:
          name: microshift-pvc
      evictionStrategy: LiveMigrate
