apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: microshift
  name: microshift
spec:
  running: true
  dataVolumeTemplates:
    - apiVersion: 'cdi.kubevirt.io/v1beta1'
      kind: 'DataVolume'
      metadata:
        name: 'microshift-pvc'
      spec:
        source:
          pvc:
            name: 'rhel-8.7'
            namespace: cnv-images
        storage:
          resources:
            requests:
              storage: '20Gi'
    - metadata:
        name: 'microshift-vdc'
      spec:
        pvc:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 20Gi
          volumeMode: Block
        source:
          blank: {}
  template:
    metadata:
      labels:
        kubevirt.io/vm: microshift
    spec:
      domain:
        machine:
          type: pc-q35-rhel8.6.0
        cpu:
          cores: 1
        devices:
          disks:
          - name: pvcdisk
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
          - disk:
              bus: virtio
            name: microshift-vdc
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 2Gi
      networks:
      - name: default
        pod: {}
      volumes:
      - name: cloudinitdisk
        cloudInitNoCloud:
          secretRef:
            name: microshift-userdata
      - name: pvcdisk
        dataVolume:
          name: microshift-pvc
      - name: microshift-vdc
        dataVolume:
          name: microshift-vdc
      livenessProbe:
        initialDelaySeconds: 120
        periodSeconds: 20
        httpGet:
          port: 1500
        timeoutSeconds: 10

      evictionStrategy: LiveMigrate
