apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: microshift
  name: microshift
spec:
  running: true
  dataVolumeTemplates:
    - apiVersion: 'cdi.kubevirt.io/v1beta1'
      kind: 'DataVolume'
      metadata:
        name: 'microshift-pvc'
      spec:
        source:
          pvc:
            name: 'rhel-8.7'
            namespace: cnv-images
        storage:
          resources:
            requests:
              storage: '20Gi'  
  template:
    metadata:
      labels:
        kubevirt.io/vm: microshift
    spec:
      domain:
        machine:
          type: pc-q35-rhel8.6.0
        cpu:
          cores: 1
        devices:
          disks:
          - name: pvcdisk
            disk:
              bus: virtio
          - disk:
              bus: virtio
            name: cloudinitdisk                
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 2Gi
      networks:
      - name: default
        pod: {}
      volumes:
      - name: pvcdisk
        dataVolume:
          name: microshift-pvc
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            user: root
            password: P@ssw0rd
            chpasswd: { expire: False }
            runcmd:
            - curl -k -o katello-ca-consumer-latest.noarch.rpm https://{{ .Values.agnosticv.satellite_url }}/pub/katello-ca-consumer-latest.noarch.rpm
            - rpm -Uhv katello-ca-consumer-latest.noarch.rpm
            - subscription-manager register --org={{.Values.agnosticv.satellite_org}} --activationkey={{.Values.agnosticv.satellite_activationkey}} --serverurl=https://{{ .Values.agnosticv.satellite_url }}:8443/rhsm/ 
            - subscription-manager repos --enable rhocp-4.12-for-rhel-8-x86_64-rpms --enable fast-datapath-for-rhel-8-x86_64-rpms
            - dnf install -y microshift
            - echo "{{.Values.agnosticv.ocp4_pull_secret }}" > /etc/crio/openshift-pull-secret
            - chown root:root /etc/crio/openshift-pull-secret
            - chmod 600 /etc/crio/openshift-pull-secret
            - systemctl enable --now microshift
        name: cloudinitdisk          
      evictionStrategy: LiveMigrate
