apiVersion: v1
kind: ConfigMap
metadata:
  name: userinfo
data:
  msg: |
    init
    {{ range $index, $service := (lookup "v1" "Service" "bring-your-demo-b9794" "").items }}
       hello
    {{ end }}

