apiVersion: v1
kind: ConfigMap
metadata:
  name: userinfo
data:
  wait_tasks: |+
   - name: Check if microshift API is ready (max 5min)
     uri:
       url: {{`https://{{ object_info.Route_microshift.spec.host }}/readyz`}}
     register: result
     until: "result.status == 200"
     validate_certs: false
     retries: 30
     delay: 10
  
  objects: |+
    - kind: Service
      name: microshift
    - kind: Route
      name: microshift
  msg: |+
    {{`
    To login: ssh root@ssh.metal.dev.redhatworkshops.io -p {{ object_info.Service_microshift.spec.ports[0].nodePort }}

    Password is `}}{{.Values.agnosticv.common_password }}{{`

    The API access is https://{{ object_info.Route_microshift.spec.host }}
    `}}
