apiVersion: v1
kind: ConfigMap
metadata:
  name: userinfo
data:
  msg: |
    {{ range $index, $service := (lookup "v1" "Service" "bring-your-demo-b9794" "").items }}
       {{ $service }}
    {{ end }}

